name: Deploy

on:
  push:
    branches: [deploy] # deploy branchì— ë¨¸ì§€í–ˆì„ ë•Œ ì‹¤í–‰

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: ğŸ’¾ Cache Gradle & Spring
        uses: actions/cache@v3
        with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

      - name: Set YML
        run: |
          cd common
          ls -l
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_LOCAL}}" | base64 --decode > src/main/resources/application-local.yml
          echo "${{ secrets.APPLICATION_LOCAL_DB }}" | base64 --decode > src/main/resources/application-local-db.yml
          echo "${{ secrets.APPLICATION_LOCAL_TOKEN }}" | base64 --decode > src/main/resources/application-local-token.yml

          echo "${{ secrets.DEPLOY }}" | base64 --decode > src/main/resources/application-deploy.yml
          echo "${{ secrets.DEPLOY_DB }}" | base64 --decode > src/main/resources/application-deploy-db.yml
          echo "${{ secrets.DEPLOY_JWT_TOKEN }}" | base64 --decode > src/main/resources/application-deploy-token.yml
          echo "${{ secrets.FIREBASE }}" | base64 --decode > src/main/resources/firebase.json
          find src

      # Gradle wrapper íŒŒì¼ ì‹¤í–‰ ê¶Œí•œì£¼ê¸°
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ğŸ”§ Build Spring server
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      # í…ŒìŠ¤íŠ¸ í›„ ìŠ¤ì›¨ì–´ ë¬¸ì„œë¥¼ ìƒì„±í•œë‹¤.
      - name: Generate Swagger Document
        run: |
          ./gradlew --info test
          ./gradlew mergeApiSpecs
          ./gradlew openapi3
          ./gradlew customGenerateSwaggerUI
          ls

      # ìŠ¤ì›¨ê±°ë¥¼ ì—…ë¡œë“œí•œë‹¤.
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'  # ë¦¬ì „ ì •ë³´
          SOURCE_DIR: 'swagger-ui-watermelon'  # ì—…ë¡œë“œí•  íŒŒì¼ë“¤ì´ ìœ„ì¹˜í•œ ë¡œì»¬ ë””ë ‰í† ë¦¬
          AWS_S3_BUCKET: 'watermelon-s3-bucket'  # S3 ë²„í‚· ì´ë¦„

      - name: Check if common directory changed
        id: check_common
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^common/'; then
            echo "common_changed=true" >> $GITHUB_ENV
          else
            echo "common_changed=false" >> $GITHUB_ENV
          fi

      - name: Check if lottery directory changed
        id: check_lottery
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^lottery/'; then
            echo "lottery_changed=true" >> $GITHUB_ENV
          else
            echo "lottery_changed=false" >> $GITHUB_ENV
          fi

      - name: Check if order directory changed
        id: check_order
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^order/'; then
            echo "order_changed=true" >> $GITHUB_ENV
          else
            echo "order_changed=false" >> $GITHUB_ENV
          fi

      - name: Check if gateway directory changed
        id: check_gateway
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^gateway/'; then
            echo "gateway_changed=true" >> $GITHUB_ENV
          else
            echo "gateway_changed=false" >> $GITHUB_ENV
          fi

      # ê²Œì´íŠ¸ì›¨ì´ ë°°í¬
      - name: deploy gateway in aws
        if: env.gateway_changed == 'true'  # ì¡°ê±´ ì„¤ì •: common ë””ë ‰í† ë¦¬ì— ë³€ê²½ì´ ìˆì„ ë•Œë§Œ ì‹¤í–‰
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          script: |
            cd /home/runner/work/Team5-WatermelonClap-BE/Team5-WatermelonClap-BE/gateway
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker build --no-cache --platform linux/arm64 -t app .
            
            docker tag app ${{secrets.DOCKER_USERNAME}}/watermelon-api-gateway:latest
            docker push ${{secrets.DOCKER_USERNAME}}/watermelon-api-gateway:latest
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/watermelon:latest
            docker tag ${{ secrets.DOCKER_USERNAME }}/watermelon:latest watermelon:latest
            docker stop $(docker ps -a -q)

            docker run -i -d --log-driver=awslogs --log-opt awslogs-region=ap-northeast-2 --log-opt awslogs-group=watermelon-cloudwatch  --log-opt awslogs-stream=watermelon-api -p 8080:8080 watermelon:latest

            docker rm $(docker ps --filter 'status=exited' -a -q)
            # ì‹¤í–‰ ì¤‘ì´ì§€ ì•Šìœ¼ ëª¨ë“  ì»¨í…Œì¸ ì‚­ì œ
            docker image prune -a -f
            # ì‚¬ìš©í•˜ì§€ì•Šì€ ëª¨ë“  ì´ë¯¸ì§€ ì‚­ì œ

      # ì¶”ì²¨ ì„œë²„ ë°°í¬
      - name: deploy lottery in aws
        if: env.lottery_changed == 'true' || env.commom_changed == 'true'
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.SSH_API_LOTTERY_HOST}}
          username: ${{secrets.SSH_USER}}
          script: |
            cd /home/runner/work/Team5-WatermelonClap-BE/Team5-WatermelonClap-BE/lottery
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker build --no-cache -t app .
  
            docker tag app ${{secrets.DOCKER_USERNAME}}/watermelon:latest
            docker push ${{secrets.DOCKER_USERNAME}}/watermelon:latest
            
            docker pull ${{ secrets.DOCKER_USERNAME }}/watermelon-api-lottery:latest
            docker tag ${{ secrets.DOCKER_USERNAME }}/watermelon-api-lottery:latest watermelon-api-lottery:latest
            docker stop $(docker ps -a -q) 

            docker run -i -d --log-driver=awslogs --log-opt awslogs-region=ap-northeast-2 --log-opt awslogs-group=watermelon-cloudwatch  --log-opt awslogs-stream=watermelon-lottery -p 8091:8091 watermelon-api-lottery:latest

            docker rm $(docker ps --filter 'status=exited' -a -q)
            # ì‹¤í–‰ ì¤‘ì´ì§€ ì•Šìœ¼ ëª¨ë“  ì»¨í…Œì¸ ì‚­ì œ
            docker image prune -a -f
            # ì‚¬ìš©í•˜ì§€ì•Šì€ ëª¨ë“  ì´ë¯¸ì§€ ì‚­ì œ
            cd ..

      # ì„ ì°©ìˆœ ì„œë²„ ë°°í¬
      - name: deploy order in aws
        if: env.order_changed == 'true' || env.commom_changed == 'true'
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SSH_KEY}}
          host: ${{secrets.SSH_API_ORDER_HOST}}
          username: ${{secrets.SSH_USER}}
          script: |
            cd /home/runner/work/Team5-WatermelonClap-BE/Team5-WatermelonClap-BE/order
            docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            docker build --no-cache --platform linux/arm64/v8 -t app .
            
            docker tag app ${{secrets.DOCKER_USERNAME}}/watermelon-api-order:latest
            docker push ${{secrets.DOCKER_USERNAME}}/watermelon-api-order:latest
              
            docker pull ${{ secrets.DOCKER_USERNAME }}/watermelon-api-order:latest
            docker tag ${{ secrets.DOCKER_USERNAME }}/watermelon-api-order:latest watermelon-api-order:latest
            docker stop $(docker ps -a -q) 

            docker run -i -d --log-driver=awslogs --log-opt awslogs-region=ap-northeast-2 --log-opt awslogs-group=watermelon-cloudwatch  --log-opt awslogs-stream=watermelon-order -p 8092:8092 watermelon-api-order:latest

            docker rm $(docker ps --filter 'status=exited' -a -q)
            # ì‹¤í–‰ ì¤‘ì´ì§€ ì•Šìœ¼ ëª¨ë“  ì»¨í…Œì¸ ì‚­ì œ
            docker image prune -a -f
            # ì‚¬ìš©í•˜ì§€ì•Šì€ ëª¨ë“  ì´ë¯¸ì§€ ì‚­ì œ